insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Jaki jest ulubiony owoc żołnierza ?', 'Granat');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Dlaczego woda nie zdała egzaminu ?', 'Bo oblała');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Jak nazywa się wóż, którym jeździ radio ?', 'Radiowóz');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Gdzie bociany chodzą na zakupy ?', 'Do żabki');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Ile zarabia mechanik samochodowy ?', '4 kołą');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Co mówi strateg, gdy przykłada ucho do zegarka ?', 'Taktyka');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Co mówi elektryk do przyjaciela ?', 'Będziemy w kontakcie');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Jak nazywa się kawa z trzech Espresso ?', 'Strzykawka');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Co robi zaatokowany kucharz ?', 'Wzywa posiłki');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Jak nazywa się lekarz, który leczy pandy ?', 'Pandoktor');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Jak wabi się pies złomiarza ?', 'Puszek');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Ulubiony baton informatyka ?', '3 bit');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Co robi piłkarz na ulicy ?', 'Stoi w korkach');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Jak nazywa się włączone radio ?', 'Radioaktywne');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Co robi 9 złotych w protfelu ?', 'Ledwo dycha');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Jak Staś żegna Nel ?', 'Panel');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Ulubiony owoc prokuratora ?', 'Winny');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Jak nazywa się rozmowa wędkarzy ?', 'Pogawędka');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Co mówi podłoga po remoncie ?', 'Jestem wykończona');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Co mówi wkurzony ogrodnik do kumpla ?', 'Przesadziłeś');

commit ;