insert INTO QUESTION (id, question) values (nextval('quest_seq'), 'WIĘCEJ NIŻ JEDNO ZWIERZĘ TO?: ');
insert INTO QUESTION (id, question) values (nextval('quest_seq'), 'JAKI PRZEDMIOT SZKOLNY NAJMNIEJ PRZYDAJE SIĘ W ŻYCIU?: ');
insert INTO QUESTION (id, question) values (nextval('quest_seq'), 'CO WIĘKSZOŚĆ LUDZI ROBI RAZ W TYGODNIU?: ');
insert INTO QUESTION (id, question) values (nextval('quest_seq'), 'CO MOŻNA KUPIĆ ZA MNIEJ NIŻ ZŁOTÓWKĘ?: ');
insert INTO QUESTION (id, question) values (nextval('quest_seq'), 'NAZWIJ PŁYN W KUCHNI, KTÓREGO LEPIEJ NIE PIĆ: ');
insert INTO QUESTION (id, question) values (nextval('quest_seq'), 'NAZWIJ ZNANYCH CZARODZIEJÓW: ');
insert INTO QUESTION (id, question) values (nextval('quest_seq'), 'JAKIE MEBLE MOGĄ BYĆ ROBIONE RĘCZNIE?: ');
insert INTO QUESTION (id, question) values (nextval('quest_seq'), 'NAZWIJ POSTACIE Z AVENGERSÓW: ');
insert INTO QUESTION (id, question) values (nextval('quest_seq'), 'ILE TRWA CHWILA?: ');
insert INTO QUESTION (id, question) values (nextval('quest_seq'), 'PODAJ POWÓD SPÓŹNIENIA DO PRACY: ');
insert INTO QUESTION (id, question) values (nextval('quest_seq'), 'CZEGO UNIKAĆ PODCZAS KEMPINGU W LESIE: ');
insert INTO QUESTION (id, question) values (nextval('quest_seq'), 'PODAJ INSTRUMENT WYSTĘPUJĄCY W ORKIESTRZE: ');
insert INTO QUESTION (id, question) values (nextval('quest_seq'), 'PODAJ CZĘŚĆ UBIORU, KTÓRY KUPUJESZ BEZ PRZYMIERZANIA: ');
insert INTO QUESTION (id, question) values (nextval('quest_seq'), 'CO TRZYMAMY W PORFELU?: ');
insert INTO QUESTION (id, question) values (nextval('quest_seq'), 'PODAJ BRÓŃ, KTÓRĄ SIĘ RZUCA: ');
insert INTO QUESTION (id, question) values (nextval('quest_seq'), 'PRZED CZYM NAJCZĘŚCIEJ UCIEKA SIĘ W FILMACH?: ');
insert INTO QUESTION (id, question) values (nextval('quest_seq'), 'CO KUPUJĄ BOGACI LUDZIE ABY POKAZAĆ, ŻE SĄ BOGACI?: ');
insert INTO QUESTION (id, question) values (nextval('quest_seq'), 'CO ROBIMY W ŚWIĘTA?: ');
insert INTO QUESTION (id, question) values (nextval('quest_seq'), 'PODAJ MIEJSCE, W KTÓRYCH NALEŻY ZACHOWAĆ CISZĘ: ');
insert INTO QUESTION (id, question) values (nextval('quest_seq'), 'CO MOŻNA ZNALEŹĆ W OPUSZCZONYM DOMU?: ');
insert INTO QUESTION (id, question) values (nextval('quest_seq'), 'CZEGO LEPIEJ NIE ZAPOMNIEĆ WYCHODZĄC Z DOMU?: ');
insert INTO QUESTION (id, question) values (nextval('quest_seq'), 'PODAJ MIEJSCA, W KTÓRYCH NIE WOLNO NIC DOTYKAĆ: ');
insert INTO QUESTION (id, question) values (nextval('quest_seq'), 'CZEGO NAJLEPIEJ SZUKAC NA BEZLUDNEJ WYSPIE?: ');
insert INTO QUESTION (id, question) values (nextval('quest_seq'), 'PODAJ ZWIERZĘ NA LITERĘ "M": ');
insert INTO QUESTION (id, question) values (nextval('quest_seq'), 'Z JAKIEJ OKAZJI ORGANIZUJEMY IMPREZY?: ');
insert INTO QUESTION (id, question) values (nextval('quest_seq'), 'PODAJ ZAWÓD NA LITERĘ "T": ');
insert INTO QUESTION (id, question) values (nextval('quest_seq'), 'JAKIEJ CZĘŚCI CIAŁA MOŻE BRAKOWAC PIRATOWI?: ');
insert INTO QUESTION (id, question) values (nextval('quest_seq'), 'CO TRACIMY GDY SIĘ STARZEJEMY?: ');
insert INTO QUESTION (id, question) values (nextval('quest_seq'), 'PODAJ POWÓD, DLA KTÓREGO BUDZIMY SIĘ W NOCY?: ');
insert INTO QUESTION (id, question) values (nextval('quest_seq'), 'PODAJ OWOC, KTÓRY SMAKUJE LEPIEJ W CZEKOLADZIE?: ');

insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 1, 'OWCA', 40);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 1, 'LAMA', 30);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 1, 'STADO', 15);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 1, 'WATAHA', 8);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 2, 'KANAPKA', 36);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 2, 'LINIJKA', 30);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 2, 'HISTORIA', 10);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 2, 'RELIGIA', 1);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 3, 'CHODZI DO KOSCIOŁA', 35);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 3, 'PRANIE', 26);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 3, 'ZAKUPY', 15);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 3, 'PORZĄDKI', 10);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 4, 'GUMĘ KULKĘ', 44);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 4, 'BUŁKĘ', 37);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 4, 'ZAPAŁKI', 15);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 4, 'ZNACZEK POCZTOWY', 5);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 5, 'PŁYN DO NACZYŃ', 46);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 5, 'OCET', 30);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 5, 'OLEJ', 16);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 5, 'POMYJE', 6);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 6, 'GANDALF', 50);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 6, 'HARRY POTTER', 41);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 6, 'MERLIN', 27);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 6, 'WRÓŻKA CHRZESTNA', 10);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 7, 'STÓŁ', 41);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 7, 'KRZESŁO', 31);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 7, 'SZAFA', 15);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 7, 'ŁÓŻKO', 5);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 8, 'IRONMAN', 45);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 8, 'THOR', 31);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 8, 'KAPITAN AMERYKA', 28);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 8, 'CZARNA WDOWA', 15);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 9, 'CHWILE', 30);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 9, 'TROCHĘ', 21);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 9, 'MOMENT', 9);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 9, 'SEKUNDE', 4);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 10, 'KORKI', 36);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 10, 'ZASPANIE', 23);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 10, 'ZŁA POGODA', 11);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 10, 'KAC', 3);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 11, 'NIEDŹWIEDZI', 40);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 11, 'ROBAKÓW', 31);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 11, 'WĘŻY', 20);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 11, 'POŻARU', 9);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 12, 'SKRZYPCE', 50);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 12, 'FLET', 20);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 12, 'KLARNET', 11);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 12, 'BĘBNY', 5);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 13, 'SKARPETKI', 38);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 13, 'BIELIZNA', 24);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 13, 'SZALIK', 10);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 13, 'CZAPKA', 3);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 14, 'PIENIĄDZE', 46);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 14, 'PRAWO JAZDY', 18);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 14, 'KARTY KREDYTOWE', 15);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 14, 'ZDJĘCIA', 10);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 15, 'SHURIKEN', 41);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 15, 'NÓŻ', 26);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 15, 'GRANAT', 15);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 15, 'WŁÓCZNIA', 5);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 16, 'POTWORY', 33);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 16, 'POLICJA', 22);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 16, 'PSY', 11);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 16, 'SAMOCHÓD', 10);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 17, 'SAMOCHÓD', 44);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 17, 'DOM', 30);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 17, 'BIŻUTERIA', 13);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 17, 'ŁÓDŹ', 5);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 18, 'UBIERAMY CHOINKĘ', 30);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 18, 'ŚPIEWAMY KOLĘDY', 16);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 18, 'ROZDAJEMY PREZENTY', 5);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 18, 'IDZIEMY DO KOŚCIOŁA', 1);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 19, 'BIBLIOTEKA', 45);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 19, 'KINO', 28);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 19, 'SZPITAL', 19);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 19, 'KOŚCIÓŁ', 10);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 20, 'PAJĘCZYNY', 28);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 20, 'KURZ', 14);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 20, 'SZCZURY', 7);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 20, 'DUCHY', 3);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 21, 'TELEFON', 42);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 21, 'PORTFEL', 35);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 21, 'KLUCZE OD ODMU', 21);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 21, 'KLUCZYKI DO AUTA', 16);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 22, 'MUZEUM', 38);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 22, 'GALERIA SZTUKI', 19);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 22, 'ZOO', 10);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 22, 'STRIPCLUB', 5);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 23, 'WODY', 50);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 23, 'JEDZENIA', 37);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 23, 'SCHRONIENIA', 20);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 23, 'POMOCY', 11);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 24, 'MAŁPA', 45);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 24, 'MYSZ', 29);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 24, 'MUCHA', 14);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 24, 'MOTYL', 8);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 25, 'ŚLUB', 41);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 25, 'URODZINY', 21);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 25, 'ROCZNICA', 10);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 25, 'AWANS W PRACY', 4);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 26, 'TOKARZ', 30);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 26, 'TYNKARZ', 17);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 26, 'TRAMWAJARZ', 9);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 26, 'TANCERZ', 5);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 27, 'NOGI', 29);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 27, 'OKA', 18);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 27, 'DŁONI', 10);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 27, 'ZĘBA', 4);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 28, 'WŁOSY', 38);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 28, 'WZROK', 20);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 28, 'ZDROWIE', 16);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 28, 'PAMIĘĆ', 9);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 29, 'ZŁY SEN', 29);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 29, 'PEŁEN PĘCHERZ', 16);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 29, 'PŁACZ DZIECKA', 11);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 29, 'HAŁAS', 8);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 30, 'TRUSKAWKA', 50);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 30, 'BANAN', 37);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 30, 'POMARAŃCZA', 20);
insert INTO ANSWER(id, question_id, answer, points) values(nextval('answer_seq'), 30, 'MALINA', 12);

insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Jaki jest ulubiony owoc żołnierza ?', 'Granat');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Dlaczego woda nie zdała egzaminu ?', 'Bo oblała');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Jak nazywa się wóż, którym jeździ radio ?', 'Radiowóz');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Gdzie bociany chodzą na zakupy ?', 'Do żabki');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Ile zarabia mechanik samochodowy ?', '4 kołą');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Co mówi strateg, gdy przykłada ucho do zegarka ?', 'Taktyka');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Co mówi elektryk do przyjaciela ?', 'Będziemy w kontakcie');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Jak nazywa się kawa z trzech Espresso ?', 'Strzykawka');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Co robi zaatokowany kucharz ?', 'Wzywa posiłki');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Jak nazywa się lekarz, który leczy pandy ?', 'Pandoktor');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Jak wabi się pies złomiarza ?', 'Puszek');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Ulubiony baton informatyka ?', '3 bit');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Co robi piłkarz na ulicy ?', 'Stoi w korkach');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Jak nazywa się włączone radio ?', 'Radioaktywne');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Co robi 9 złotych w protfelu ?', 'Ledwo dycha');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Jak Staś żegna Nel ?', 'Panel');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Ulubiony owoc prokuratora ?', 'Winny');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Jak nazywa się rozmowa wędkarzy ?', 'Pogawędka');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Co mówi podłoga po remoncie ?', 'Jestem wykończona');
insert INTO JOKES (id, joke, answer) values (nextval ('jokes_seq'), 'Co mówi wkurzony ogrodnik do kumpla ?', 'Przesadziłeś');

insert INTO USER (user_id, username, score) values (nextval('user_seq'), 'JarczaN', 0);
insert INTO USER (user_id, username, score) values (nextval('user_seq'), 'TOMMMTO', 0);
insert INTO USER (user_id, username, score) values (nextval('user_seq'), 'megula22', 0);
insert INTO USER (user_id, username, score) values (nextval('user_seq'), 'Julita468', 0);

commit ;