insert INTO QUESTION (id, question, answer1, points1, answer2, points2, answer3, points3, answer4, points4) values (nextval('quest_seq'), 'WIECEJ NIZ JEDNO ZWIERZE TO: ', 'OWCA', 40, 'LAMA', 30, 'STADO', 15, 'WATAHA', 8);
insert INTO QUESTION (id, question, answer1, points1, answer2, points2, answer3, points3, answer4, points4) values (nextval('quest_seq'), 'JAKI PRZEDMIOT SZKOLNY NAJMNIEJ PRZYDAJE SIE W ZYCIU?: ', 'KANAPKA', 36, 'LINIJKA', 30, 'HISTORIA', 10, 'RELIGIA', 1);
insert INTO QUESTION (id, question, answer1, points1, answer2, points2, answer3, points3, answer4, points4) values (nextval('quest_seq'), 'CO WIEKSZOSC LUDZI ROBI RAZ W TYGODNIU?: ', 'CHODZI DO KOSCIOLA', 35, 'PRANIE', 26, 'ZAKUPY', 15, 'PORZADKI', 10);
insert INTO QUESTION (id, question, answer1, points1, answer2, points2, answer3, points3, answer4, points4) values (nextval('quest_seq'), 'CO MOZNA KUPIC ZA MNIEJ NIZ ZLOTOWKE?: ', 'GUME KULKE', 44, 'BULKE', 37, 'ZAPALKI', 15, 'ZNACZEK POCZTOWY', 5);
insert INTO QUESTION (id, question, answer1, points1, answer2, points2, answer3, points3, answer4, points4) values (nextval('quest_seq'), 'NAZWIJ PLYN W KUCHNI, KTOREGO LEPIEJ NIE PIC: ', 'PLYN DO NACZYN', 46, 'OCET', 30, 'OLEJ', 16, 'POMYJE', 6);
insert INTO QUESTION (id, question, answer1, points1, answer2, points2, answer3, points3, answer4, points4) values (nextval('quest_seq'), 'NAZWIJ ZNANYCH CZARODZIEJOW: ', 'GANDALF', 50, 'HARRY POTTER', 41, 'MERLIN', 27, 'WROZKA CHRZESTNA', 10);
insert INTO QUESTION (id, question, answer1, points1, answer2, points2, answer3, points3, answer4, points4) values (nextval('quest_seq'), 'JAKIE MEBLE MOGA BYC ROBIONE RECZNIE?: ', 'STOL', 41, 'KRZESLO', 31, 'SZAFA', 15, 'LOZKO', 5);
insert INTO QUESTION (id, question, answer1, points1, answer2, points2, answer3, points3, answer4, points4) values (nextval('quest_seq'), 'NAZWIJ POSTACI Z AVENGERSOW: ', 'IRONMAN', 45, 'THOR', 31, 'CAPITAN AMERICA', 28, 'BLACK WIDOW', 15);
insert INTO QUESTION (id, question, answer1, points1, answer2, points2, answer3, points3, answer4, points4) values (nextval('quest_seq'), 'ILE TRWA CHWILA?: ', 'CHWILE', 25, 'TROCHE', 17, 'MOMENT', 6, 'SEKUNDE', 3);
insert INTO QUESTION (id, question, answer1, points1, answer2, points2, answer3, points3, answer4, points4) values (nextval('quest_seq'), 'PODAJ POWOD SPOZNIENIA DO PRACY: ', 'KORKI', 36, 'ZASPANIE', 23, 'ZLA POGODA', 11, 'KAC', 3);

commit ;